2020-11-30 17:21:50,975 server      : ERROR Exception on /api/v1/totp [GET]
Traceback (most recent call last):
  File "C:\Users\Lokesh.P\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\Lokesh.P\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
    raise err
  File "C:\Users\Lokesh.P\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
OSError: [WinError 10065] A socket operation was attempted to an unreachable host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lokesh.P\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Lokesh.P\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Lokesh.P\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "C:\Users\Lokesh.P\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 309, in connect
    conn = self._new_conn()
  File "C:\Users\Lokesh.P\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000002296EF9DCA0>: Failed to establish a new connection: [WinError 10065] A socket operation was attempted to an unreachable host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lokesh.P\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\Lokesh.P\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "C:\Users\Lokesh.P\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='tecnics-dev.oktapreview.com', port=443): Max retries exceeded with url: /oauth2/ausuvcipegUUQa9Bk0h7/v1/introspect?client_id=0oauvb74ocd6zt1Yh0h7 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002296EF9DCA0>: Failed to establish a new connection: [WinError 10065] A socket operation was attempted to an unreachable host'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lokesh.P\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Lokesh.P\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Lokesh.P\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Lokesh.P\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Lokesh.P\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Lokesh.P\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1948, in full_dispatch_request
    rv = self.preprocess_request()
  File "C:\Users\Lokesh.P\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2242, in preprocess_request
    rv = func()
  File "server.py", line 52, in check_token_header
    is_token_valid, token_info = introspect(request.headers[TOKEN])
  File "server.py", line 125, in introspect
    response = get_token_info(token)
  File "server.py", line 136, in get_token_info
    response = requests.post(url, data=body)
  File "C:\Users\Lokesh.P\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\Lokesh.P\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Lokesh.P\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Lokesh.P\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Lokesh.P\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='tecnics-dev.oktapreview.com', port=443): Max retries exceeded with url: /oauth2/ausuvcipegUUQa9Bk0h7/v1/introspect?client_id=0oauvb74ocd6zt1Yh0h7 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002296EF9DCA0>: Failed to establish a new connection: [WinError 10065] A socket operation was attempted to an unreachable host'))
2020-11-30 17:21:51,390 server      : INFO 127.0.0.1 GET /api/v1/totp http 500 INTERNAL SERVER ERROR 290 http://localhost:3000/ Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
2020-11-30 17:21:51,391 werkzeug    : INFO 127.0.0.1 - - [30/Nov/2020 17:21:51] "[35m[1mGET /api/v1/totp HTTP/1.1[0m" 500 -
2020-11-30 19:08:28,832 server      : INFO 127.0.0.1 OPTIONS /api/v1/totp http 200 OK 3 http://localhost:3000/ Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
2020-11-30 19:08:28,840 werkzeug    : INFO 127.0.0.1 - - [30/Nov/2020 19:08:28] "[37mOPTIONS /api/v1/totp HTTP/1.1[0m" 200 -
2020-11-30 19:08:31,087 server      : INFO OKTA INTROSPECT URL: https://tecnics-dev.oktapreview.com/oauth2/ausuvcipegUUQa9Bk0h7/v1/introspect?client_id=0oauvb74ocd6zt1Yh0h7
2020-11-30 19:08:31,087 server      : INFO OKTA INTROSPECT STATUSCODE: 200
2020-11-30 19:08:31,088 server      : INFO TOKEN STATUS: True
2020-11-30 19:08:31,090 server      : INFO 127.0.0.1 GET /api/v1/totp http 200 OK 105 http://localhost:3000/ Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
2020-11-30 19:08:31,092 werkzeug    : INFO 127.0.0.1 - - [30/Nov/2020 19:08:31] "[37mGET /api/v1/totp HTTP/1.1[0m" 200 -
2020-11-30 19:08:33,028 server      : INFO OKTA INTROSPECT URL: https://tecnics-dev.oktapreview.com/oauth2/ausuvcipegUUQa9Bk0h7/v1/introspect?client_id=0oauvb74ocd6zt1Yh0h7
2020-11-30 19:08:33,028 server      : INFO OKTA INTROSPECT STATUSCODE: 200
2020-11-30 19:08:33,028 server      : INFO TOKEN STATUS: True
2020-11-30 19:08:33,028 server      : INFO 127.0.0.1 GET /api/v1/totp http 200 OK 105 http://localhost:3000/ Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
2020-11-30 19:08:33,028 werkzeug    : INFO 127.0.0.1 - - [30/Nov/2020 19:08:33] "[37mGET /api/v1/totp HTTP/1.1[0m" 200 -
2020-11-30 19:08:35,589 server      : INFO OKTA INTROSPECT URL: https://tecnics-dev.oktapreview.com/oauth2/ausuvcipegUUQa9Bk0h7/v1/introspect?client_id=0oauvb74ocd6zt1Yh0h7
2020-11-30 19:08:35,590 server      : INFO OKTA INTROSPECT STATUSCODE: 200
2020-11-30 19:08:35,590 server      : INFO TOKEN STATUS: True
2020-11-30 19:08:35,593 server      : INFO 127.0.0.1 GET /api/v1/totp http 200 OK 105 http://localhost:3000/ Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
2020-11-30 19:08:35,594 werkzeug    : INFO 127.0.0.1 - - [30/Nov/2020 19:08:35] "[37mGET /api/v1/totp HTTP/1.1[0m" 200 -
2020-12-01 19:06:32,043 werkzeug    : INFO  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2020-12-01 19:08:27,788 server      : INFO OKTA INTROSPECT URL: https://tecnics-dev.oktapreview.com/oauth2/ausuvcipegUUQa9Bk0h7/v1/introspect?client_id=0oauvb74ocd6zt1Yh0h7
2020-12-01 19:08:27,789 server      : INFO OKTA INTROSPECT STATUSCODE: 200
2020-12-01 19:08:27,789 server      : INFO TOKEN STATUS: True
2020-12-01 19:08:27,795 server      : INFO 127.0.0.1 POST /api/v1/secret http 200 OK 17 None PostmanRuntime/7.26.8
2020-12-01 19:08:27,798 werkzeug    : INFO 127.0.0.1 - - [01/Dec/2020 19:08:27] "[37mPOST /api/v1/secret HTTP/1.1[0m" 200 -
2020-12-01 19:09:08,732 server      : INFO OKTA INTROSPECT URL: https://tecnics-dev.oktapreview.com/oauth2/ausuvcipegUUQa9Bk0h7/v1/introspect?client_id=0oauvb74ocd6zt1Yh0h7
2020-12-01 19:09:08,733 server      : INFO OKTA INTROSPECT STATUSCODE: 200
2020-12-01 19:09:08,734 server      : INFO TOKEN STATUS: True
2020-12-01 19:09:08,741 server      : INFO 127.0.0.1 POST /api/v1/secret http 200 OK 17 None PostmanRuntime/7.26.8
2020-12-01 19:09:08,743 werkzeug    : INFO 127.0.0.1 - - [01/Dec/2020 19:09:08] "[37mPOST /api/v1/secret HTTP/1.1[0m" 200 -
2020-12-02 14:46:40,311 werkzeug    : INFO  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
